FROM python:3.9-slim

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /app

COPY grpc_src/client.py /app/client.py
COPY generated /app/generated

# VOLUME ["/app/src"]

CMD ["python", "/app/client.py"]
